### PR TITLE
fix days off for first game

### PR DESCRIPTION
**Pull request by nkgilley**
fix for https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/issues/292

### CODE REVIEW

**Comment by Vereece** [comment]
Hello Kyle,
Your model seems to be having issues this season please fix it.

**Comment by ethan-hurst** [comment]
Hi Vereece, 

Maybe fix it yourself.

**Comment by kyleskom** [comment]
@Vereece if you are having issues open a new issue and provide something more then "im having issues please fix it"

**Comment by Vereece** [comment]
Hello Ethan,
I'm so sorry you to my comment the wrong way, I didn't really mean to sound
ungrateful. I actually go to know about this tool from a YouTube video this
year. So I used it last season but when I tried to use it this season it
was having issues, so initially I sent a message to the YouTube to help me
rectify the issue but he didn't answer so I had to trace it back to you. It
would be really nice if you helped to fix it.
So sorry we got to start on the wrong foot.

I'm Emmanuel.

**Comment by ethan-hurst** [comment]
Hi Emmanuel. 

You've not actually told anyone here what issue you have encountered.

**Pull request merged**
