### PR TITLE
Second PR for Kelly Criterion to give suggested wager amounts

### PR DESCRIPTION
**Pull request by AaronAshery**
First PR: https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/pull/221

Currently the model ignores EV to pick its winner. People want to use this tool to place wagers, and smart wagering is based on expected value. Kelly Criterion suggests an amount to wager taking into account the EV as well as the odds.
I have not ran any tests on data but I can assume that based on the spreadsheet tracking the success, it would be higher following Kelly wagering. I have the output as follows:

image

### CODE REVIEW

**Comment by kyleskom** [comment]
We can delete the first PR correct? This is everything?

**Comment by AaronAshery** [comment]
Yup!

**Comment by AaronAshery** [comment]
*Note that the wagers are suggested based on having a $100 bankroll. This can be adjusted as well with making the wagering more conservative in the kelly function

**Comment by timseymour42** [comment]
Hey @AaronAshery, I left a comment on the Kelly Criterion issue earlier this week that I was going to implement this feature, so I have also implemented this. In the future please make a note of what you are working on to avoid this situation. Having that said, I have tests for my implementation and I refactored some code, so I am going to create a pull request as well

**Comment by timseymour42** [comment]
> Hey @AaronAshery, I left a comment on the Kelly Criterion issue earlier this week that I was going to implement this feature, so I have also implemented this. In the future please make a note of what you are working on to avoid this situation. Having that said, I have tests for my implementation and I refactored some code, so I am going to create a pull request as well

I also implemented the Kelly Criterion for NN model as well

**Comment by AaronAshery** [comment]
> Hey @AaronAshery, I left a comment on the Kelly Criterion issue earlier this week that I was going to implement this feature, so I have also implemented this. In the future please make a note of what you are working on to avoid this situation. Having that said, I have tests for my implementation and I refactored some code, so I am going to create a pull request as well

My fault @timseymour42, I just came across the repo and liked it a lot so I added a bit to try and help out. It looks like you went more in depth, hopefully both our work can be helpful contributions!

**Comment by timseymour42** [comment]
> > Hey @AaronAshery, I left a comment on the Kelly Criterion issue earlier this week that I was going to implement this feature, so I have also implemented this. In the future please make a note of what you are working on to avoid this situation. Having that said, I have tests for my implementation and I refactored some code, so I am going to create a pull request as well
> 
> My fault @timseymour42, I just came across the repo and liked it a lot so I added a bit to try and help out. It looks like you went more in depth, hopefully both our work can be helpful contributions!

No worries man!

**Pull request closed without merging**
