### PR TITLE
fix kelly criterion

### PR DESCRIPTION
**Pull request by MorganMathy**
Hello guys, juste a little improvment on calculation from american to decimal odds that was not correct.
Have fun !

### CODE REVIEW

**Comment by kyleskom** [comment]
Do the tests need be re-written in the tests folder?

**Comment by MorganMathy** [comment]
Hello @kyleskom,
Tests are updated & functionals.
I removed test5 to be more realistic since 99% probability is involving a very large american odd.
Regards!

**Comment by MorganMathy** [comment]
i'll work a bit on tests. There are some troubles :-p

**Comment by MorganMathy** [comment]
It's done, you can review it @kyleskom

**Comment by kyleskom** [comment]
Why did you close this?

**Pull request closed without merging**
