### PR TITLE
fix 2023 data, update models

### PR DESCRIPTION
**Pull request by nkgilley**
This fixes the data issue brought up by @jfacowns in https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/discussions/135.

### CODE REVIEW

**Comment by kyleskom** [comment]
This looks to be breaking the flask app

**Comment by kyleskom** [comment]
The command line as well.

**Comment by kyleskom** [comment]
This might be because of the requirements update. What version of python was the built for?

**Comment by kyleskom** [comment]
Im on 3.9 and getting `ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.11.0
`

**Comment by kyleskom** [comment]
When trying to run command line `TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.`

**Comment by nkgilley** [comment]
Hey, so on my mac I don't install `tensorflow==2.11.0`, but rather `tensorflow-macos==2.11.0`.  I'm not sure what the best way to handle this is.  I have manually edited the requirements.txt in my local environment.  I think once xgboost is updated the errors will go away.

**Comment by kyleskom** [comment]
Oh ya oops. I forgot the m1 Macs have a special tensorflow

**Comment by kyleskom** [comment]
Hmm that didn't seem to fix it.

**Comment by kyleskom** [comment]
A fresh install of tensorflow fixed this. Sorry for confusion.

**Pull request merged**
