### PR TITLE
Kellycriterion

### PR DESCRIPTION
**Pull request by timseymour42**
In this update, I did the following:

- Created a Kelly Criterion class to calculate the percentage of the bankroll a bettor should use
- Revised the NN_Runner and XGB_Runner files to indicate the correct fraction of the bankroll for each bet
- Created a Kelly Criterion test file to ensure the calculations are accurate
- Refactored color logic in the NN_Runner and XGB_Runner files
- Updated the Readme to reflect the changes

KC Update

### CODE REVIEW

**Comment by kyleskom** [comment]
Will review this soon. One thing I'm thinking though is to have this behind a feature flag.

**Comment by fciaf420** [comment]
I am very new to this, how can I pull thos code into collab and run it to get the kelly criterion results ?

**Comment by timseymour42** [comment]
> I am very new to this, how can I pull thos code into collab and run it to get the kelly criterion results ?

You can replace the git clone command with this: git clone -b kellycriterion https://github.com/timseymour42/NBA-Machine-Learning-Sports-Betting.git

You can also plug the model's win probability into this calculator: [](https://www.sportsbookreview.com/betting-calculators/kelly-calculator/ ) The kelly criterion feature is not a part of the main code base just yet.

**Comment by timseymour42** [comment]
> Will review this soon. One thing I'm thinking though is to have this behind a feature flag.

Yeah, that's a great idea! I can implement this. Before doing so, I just want to be sure that my code would be used because there is another contributor that implemented the kelly criterion feature. So lmk.

**Comment by kyleskom** [comment]
> > Will review this soon. One thing I'm thinking though is to have this behind a feature flag.
> 
> Yeah, that's a great idea! I can implement this. Before doing so, I just want to be sure that my code would be used because there is another contributor that implemented the kelly criterion feature. So lmk.

Yup this will be used / merged if we can have this behind a feature flag.

**Comment by onlyadamscott** [comment]
Such good work. Thanks guys! I'm working on a native Sentiment agent. Still testing for accuracy.

**Comment by BG2011** [comment]
Great addition man ! Small question this will work for the money line but what about the points ?

**Comment by timseymour42** [comment]
> Great addition man ! Small question this will work for the money line but what about the points ?

Currently, the output of the models is a percentage chance that a team will win on the ML. You could raise an issue that you would like to see predictions for the point spread.

**Review by kyleskom — APPROVED** [review]
Tested and verified. Works as expected!

**Comment by kaiforsyth** [comment]
This breaks when not passing the `-odds` argument to use custom odds:
`TypeError: '>=' not supported between instances of 'str' and 'int'`

Need to convert the input to an integer.

**Pull request merged**
