### PR TITLE
Google Colab Notebook for Running Model

### PR DESCRIPTION
**Pull request by thienlongtran**
Some people, myself included, are unable to run the model due to the lack of necessary hardware and whatnot. The notebook provided in this PR allows users to run the model seamlessly and freely on Google Colab!

### CODE REVIEW

**Comment by kyleskom** [comment]
Can you give me a brief overview on how to test this?

**Comment by thienlongtran** [comment]
> Can you give me a brief overview on how to test this?

Hi Kyle!

1. Download/clone [ColabNotebook.ipynb](https://github.com/thienlongtran/NBA-Machine-Learning-Sports-Betting/blob/ColabNotebook/ColabNotebook.ipynb) which is included in this PR
2. Head over to [https://colab.research.google.com/](https://colab.research.google.com/) and upload `ColabNotebook.ipynb` as a new notebook
3. The runtime should be set to `GPU` by default, but if there's issues with it then follow these steps:
    - click on `Runtime` in the top tab
    - click on `Change runtime type`
    - set `Hardware accelerator` as `GPU`
4. Run the `Bootstrap Model` cell
5. Run the `Run Model` cell once bootstrapping is done, then the rest is 

Example: https://colab.research.google.com/drive/103DGVFZbWehI_JNHbTmqcy7VkF3h1pr2?usp=sharing

Screen Shot 2022-11-29 at 11 10 41 PM
Screen Shot 2022-11-29 at 11 11 00 PM

**Review by kyleskom — APPROVED** [review]
Tested and worked exactly as expected. Will merge.

**Comment by kyleskom** [comment]
Thank again for this PR!

**Comment by thienlongtran** [comment]
@kyleskom

Always, and thanks for your work! This is really good, inspiring stuff! Add me on LinkedIn wont ya :3

https://www.linkedin.com/in/thienlongtran/

**Pull request merged**
