### PR TITLE
add days rest

### PR DESCRIPTION
**Pull request by nkgilley**
Add days rest columns for the home and away teams.

This needs to be reviewed and tested.

### CODE REVIEW

**Comment by kyleskom** [comment]
Traveling this week so might be a little bit before I get to this.

**Comment by nkgilley** [comment]
With this model it's predicting every game to go OVER at 80%.  Something must be wrong

**Comment by kyleskom** [comment]
Do you mind resolving the conflicts, id like to test this soon.

**Comment by nkgilley** [comment]
Yea sure thing, will push an update soon

**Comment by nkgilley** [comment]
@kyleskom just pushed an update to fix the conflicts.  jfyi this training was done on my mac which may not work on x86.

**Comment by kyleskom** [comment]
After a brief look, I verified the historical data rest days look ok. (Just verified 2 teams). I also verified rest days for current games looks good. I do see what you mean with the over. Thats very strange so far. Going to take a deeper look. One thing I might recommend for this is unit tests. Add a few for random games for the historical data.

**Comment by kyleskom** [comment]
Im going to keep looking into this and training my own models on this as well.

**Comment by kyleskom** [comment]
Ok I think I see what's going on. I checked the input for the training data and it has a dimension of 107, the input data for predictions is 106. I think some field is being dropped somewhere. Ideally we need the indexes of data to match.

**Comment by kyleskom** [comment]
I got it. The index of training data and prediction data doesn't line up.
image
image

**Comment by kyleskom** [comment]
Training som new models and pushing fix soon.

**Comment by kyleskom** [comment]
My push created a new branch not from your fork.
https://github.com/kyleskom/NBA-Machine-Learning-Sports-Betting/tree/days-rest

**Comment by kyleskom** [comment]
Last steps would be to do the same fix for NN model and maybe add some tests for the rest days aspect. But other than that thank you for all this. I think this def helped improve the model.

**Pull request closed without merging**
